// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DotnetCoreApi.Models
{
    public partial class Person :ISoftDeleteable
    {
       
    }
}